description: blog.kaorimatz.org
exclude: ['.scss-lint.yml', 'CNAME', 'Gemfile', 'Gemfile.lock', 'vendor']
markdown: redcarpet
safe: true
title: blog.kaorimatz.org
url: http://blog.kaorimatz.org
sass:
  style: compressed
